name: Workflow 1

on: workflow_dispatch

jobs:
  job_1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
      - run: echo [workflow1] step 1
  job_2:
    uses: ./.github/workflows/workflow2.yml
    with:
      message: "Hello from Workflow 1"
